---
title: "TP_final"
author: "Sabrina Ariana y Micaela"
date: "12/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Análisis Covid-19

Analizamos base de covid etc etc

```{r librerias, echo=TRUE, eval=FALSE, warning=FALSE}
library(tidyverse)
library(readr)
library(harrypotter)
```


```{r base covid, echo=TRUE, eval=FALSE, warning=FALSE}
Covid_Casos <- read_csv('Covid19Casos.csv') 
```

## Transformamos tabla

```{r transformacion, echo=TRUE, eval=FALSE, warning=FALSE}
Covid_Casos2 <- Covid_Casos %>%
  group_by(residencia_provincia_nombre, clasificacion_resumen) %>%
  filter(clasificacion_resumen == 'Confirmado') %>%
  summarise(N = n())
```


## Graficamos

```{r grafico, echo=TRUE, eval=FALSE, warning=FALSE}
Covid_Casos2 %>%
  ggplot(aes(x = residencia_provincia_nombre, y = (N),
             fill = N)) + geom_bar(stat="identity") +
  coord_flip() + 
  scale_fill_hp(option = "ronweasley2", name = "Casos confirmados")  +
  labs(title = "Casos confirmados de Covid-19 por Provincia",
       x = "Cantidad de casos",
       y = "Provincia")
```

