---
title: "Trabajo Final"
author: "Bardauil, Ibarra, Zapata"
date: "13/9/2021"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 5
---

```{r setup, include=FALSE}
{r setup, include=FALSE, warning=FALSE, message = FALSE, ERROR = FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Llamamos librerias

library(tidyverse)
library(skimr)
library("lubridate")
library(nlme)
library(dplyr)

```

## 1.[**Resumen**]{.ul}

En el año 2020 una fuerte crisis sanitaria se originó por la aparición del virus SARCOV-2 y la propagación de la pandemia del COVID-19.Esta pandemia afecto la vida y la salud de la población a nivel mundial.En Argentina se han tomado diferentes medidas de aislamiento social, pero a pesar de ello, una buena parte de la población ha sido afectada, alcanzando a más de 100.000 casos de personas fallecidas.En este marco, nos interesa conocer quienes han sido las personas más vulnerables al no poder su superar la enfermedad, y encontrar algunas de las causas que podrían haber influido en su deceso.Se analizarán los factores que puedan afectar la tasa de fallecidos por COVID-19 (calculada en relación al total de casos de personas contagiadas en la región del AMBA).
Se utilizará la base pública provista por el Ministerio de Salud de la Nación, sobre la situación de la COVID-19, disponible en: <https://datos.gob.ar/dataset/salud-covid-19-casos-registrados-republica-argentina/archivo/salud_fd657d02-a33a-498b-a91b-2ef1a68b8d16>.
Esta base contiene información actualizada diariamente, a las 21:30 hs.
notificando CASOS COVID-19 registrados en el país, con un corte del día a las 17:45 hs.La fecha de bajada de la base es 11 de agosto de 2021.Se indagará cómo está compuesta la base, sus dimensiones y los tipos de valores que componen cada variable.Se transformará para poder trabajarla, dado que se trata de un data set de grandes dimensiones.
Para la etapa analítica, se generará una regresión, evaluando la medida en que diferentes variables independientes afectan a esa tasa y se explorarán como tales: la edad, el sexo, el momento en que se detectó la enfermedad, si la persona fue internada o no, si estuvo en cuidados intensivos o no y si tuvo asistencia respiratoria o no.
En particular, para poder analizar el momento de contagio, se trabajará creará una variable que vincule la semana epidemiológica con el año correspondiente, dado que las semanas epidemiológicas se reinician cada año.
Se analizarán modelos multivariados comparando la mejor aproximación de un modelo con efectos fijos y aleatorios.

## 2. [**Estructura de los datos**]{.ul}

La base covid-19 cuenta con 25 variables y 16.552.542 registros en total.
Para posibilitar su procesamiento, se reducirá el análisis a los casos clasificados como "confirmados".
**Eso reduce la cantidad de registros a 2.497.319**.
Una vez establecido este recorte, se trabajará sobre los casos correspondientes al AMBA, lo que devuelve una base de 1.252.588 registros.Como parte del análisis exploratorio, hemos observado:

Las variables de la base, son:

| **Título de la Columna**           | **Tipo de dato**       | **Descripción**                                                 |
|------------------------------------|------------------------|-----------------------------------------------------------------|
| *id_evento_caso*                   | integer                | Número de caso                                                  |
| *sexo*                             | String                 | Sexo                                                            |
| *edad*                             | Numero entero          | Edad                                                            |
| *edad_años_meses*                  | String                 | Edad indicada en meses o años                                   |
| *residencia_pais_nombre*           | string                 | pais de residencia                                              |
| *residencia_provincia_nombre*      | string                 | Provincia de residencia                                         |
| *residencia_departamento_nombre*   | string                 | Departamento de residencia                                      |
| *carga_Provincia_nombre*           | string                 | Provincia de establecimiento                                    |
| *fecha_inicio_sintomas*            | Fecha ISO-8601(date)   | Fecha de inicio de sintomas                                     |
| *fecha_Apertura*                   | Fecha ISO-8601(date)   | Fecha de apertura del caso                                      |
| *sepi_Apertura*                    | Integer                | Semana Epidemiológica de fecha de apertura                      |
| *fecha_internacion*                | Fecha ISO-8601 (date)  | Fecha de internación                                            |
| *cuidado_intensivo*                | string                 | Indicación si estuvo en cuidado intensivo                       |
| *fecha_cui_intensivo*              | Fecha ISO-8601 (date)  | Fecha de ingreso a cuidado intensivo en el caso de corresponder |
| *fallecido*                        | string                 | Indicacion de Fallecido                                         |
| *fecha_fallecimiento*              | Tiempo ISO-8601 (time) | Fecha de fallecimiento en el caso de corresponder               |
| *asistencia_respiratoria_mecanica* | string                 | Indicación si requirió asistencia respiratoria mecánica         |
| *carga_provincia_id*               | integer                | Código de Provincia de carga                                    |
| *origen_financiamiento*            | string                 | Origen de financiamiento                                        |
| *Clasificacion*                    | string                 | Clasificacion manual del registro                               |
| *clasificacion_resumen*            | string                 | clasificacion del caso                                          |
| *residencia_provincia_id*          | integer                | Codigo de Provincia de Residencia                               |
| *fecha_diagnostico*                | Tiempo ISO-8601 (time) | Fecha de diagnóstico                                            |
| *residencia_departamento_id*       | integer                | Codigo departamento de residencia                               |
